---
- name: Cleanup
  hosts: all
  tasks:
    - name: Include ravendb_node role to install RavenDB
      include_role:
        name: ravendb_node
      vars:
        ravendb_state: present
        ravendb_version: latest
        ravendb_version_minor: 6.2
        ravendb_release_channel: stable
        ravendb_arch: linux-x64
        ravendb_settings_preset: default

    - name: Wait for port 8080 to become open
      tags: node_wait_for
      wait_for:
        port: 8080
        sleep: 1
        delay: 2
        timeout: 60

    - name: Ensure alive
      retries: 10
      delay: 2
      tags: node_ensure_alive
      ansible.builtin.uri:
        url: "http://localhost:8080/setup/alive"
        method: GET
        status_code: 204

    - name: Create a database
      tags: node_create_db
      ansible.builtin.uri:
        url: "http://localhost:8080/admin/databases?name=database&replicationFactor=1"
        method: PUT
        body_format: json
        body: |
          {
            "DatabaseName": "database",
            "Settings": {}, 
            "Disabled": false,
            "Encrypted": false,
            "Topology": { "DynamicNodesDistribution": false } 
          }
        status_code: 201

- name: Cleanup
  hosts: all
  tasks:
    - name: Uninstall RavenDB
      include_role:
        name: ravendb_node
      vars:
        ravendb_state: absent
