- name: Create ravendb group
  ansible.builtin.group:
    name: ravendb
    state: present

- name: Create ravendb user
  ansible.builtin.user:
    name: ravendb
    state: present
    comment: RavenDB Server user
    groups: ravendb
    append: yes

- name: Prepare directory structure
  file:
    path: "{{ item }}"
    owner: ravendb
    group: ravendb
    mode: '0770' # TODO security, fix permissions to be like in DEB
    state: directory
  loop:
    - "/etc/ravendb"
    - "/etc/ravendb/security"
    - "/var/log/ravendb/audit"
    - "/var/log/ravendb/logs"
    - "/var/lib/ravendb"
    - "/var/lib/ravendb/nuget"
    - "/usr/lib/ravendb/server"

- name: Remove old file
  file:
    name: /tmp/ravendb.tar.bz2
    state: absent

- name: Determine download url for latest version
  set_fact:
    ravendb_download_url: "https://hibernatingrhinos.com/downloads/RavenDB%20for%20Linux%20x64/latest?buildType={{ ravendb_server_release_channel }}&version={{ ravendb_server_version_minor }}"
  when: ravendb_server_version == "latest"

- name: Determine download url for exact version
  set_fact:
    ravendb_download_url: "https://daily-builds.s3.amazonaws.com/RavenDB-{{ ravendb_server_version }}-linux-x64.tar.bz2"
  when: ravendb_server_version != ""

# TODO allow select arch
# TODO allow select version
# TODO allow select release channel
- name: Download RavenDB server binaries
  ansible.builtin.get_url:
      url: "{{ ravendb_download_url }}"
      dest: /tmp/ravendb.tar.bz2

- name: Unpack RavenDB server binaries
  ansible.builtin.unarchive:
    src: /tmp/ravendb.tar.bz2
    dest: /usr/lib/ravendb/server
    extra_opts:
        - --transform
        - s/^RavenDB\/Server//

- name: Template settings.json out 
  ansible.builtin.template:
          src: settings.json.j2
          dest: /etc/ravendb/settings.json
          owner: root # depending on whether we do setup we want ravendb or root here
          group: ravendb
          mode: '0640'

- name: Template ravendb.service out 
  ansible.builtin.template:
    src: ravendb.service.j2
    dest: /etc/systemd/system/ravendb.service
    owner: root
    group: root
    mode: '0644'

- name: Just force systemd to reread configs (2.4 and above)
  ansible.builtin.systemd:
    daemon_reload: yes