---
- name: Unsecured
  hosts: all
  tasks:
    - name: "Include ravendb_node"
      include_role:
        name: "ravendb_node"
      vars:
        ravendb_settings_preset: unsecured
        ravendb_settings_override:
          Indexing.MapBatchSize: 1024
          Logs.Mode: "Information"
