---
- name: Unsecured
  hosts: all
  tasks: 
    - name: "Include ravendb_node"
      include_role:
        name: "ravendb_node"
      vars:
        ravendb_state: present
        ravendb_version: latest
        ravendb_version_minor: 6.2
        ravendb_release_channel: stable
        ravendb_arch: linux-x64
        ravendb_settings_preset: default
        ravendb_settings_override:
          Logs.Mode: "Information"
