namespace: ravendb
name: ravendb
version: 1.0.0
readme: README.md
authors:
- Grzegorz Lachowski <gregolsky@ravendb.net>
- Omer Ratsaby <omer.ratsaby@ravendb.net>
description: An Ansible collection for deploying, configuring, and managing RavenDB clusters on Linux-based environments.
license:
- GPL-3.0-or-later
license_file: ''
tags: 
  - ravendb
  - database
  - cluster
  - nosql
  - devops
  - automation
  - ansible
  - ubuntu
  - rhel
dependencies: {}
repository: https://github.com/ravendb/ansible-collection-ravendb
documentation: https://ravendb.net/docs
homepage: https://ravendb.net
issues: https://issues.hibernatingrhinos.com
build_ignore: []