dependency:
  name: galaxy
driver:
  name: docker
  port_bindings:
    '8080': 80
    '38888': 38888
    '44443': 443
platforms:
  - name: centos
    image: 'trfore/docker-centos9-systemd'
    privileged: true
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:rw'
    tmpfs:
      - /run
      - /tmp
    command: /lib/systemd/systemd
lint: |
  set -e
  yamllint .
  ansible-lint
provisioner:
  name: ansible
  log: true
  inventory:
    host_vars:
      centos:
        node_tag: "A"
scenario:
  name: secured-rhel
  test_sequence:
    - destroy
    - create
    - converge
    - verify
verifier:
  name: ansible
