---
- name: Reset Index
  hosts: ravendb_nodes
  gather_facts: no

  roles:
    - ravendb.ravendb.ravendb_python_client_prerequisites

  tasks:
    - name: Ensure RavenDB Index is reset (check mode)
      ravendb.ravendb.index:
        url: "http://{{ ansible_host }}:8080"
        database_name: "my_database"
        index_name: "Orders/ByCompany"
        mode: reset
      check_mode: yes

    - name: Ensure RavenDB Index is reset
      ravendb.ravendb.index:
        url: "http://{{ ansible_host }}:8080"
        database_name: "my_database"
        index_name: "Orders/ByCompany"
        mode: reset
        
    - name: Ensure RavenDB Index is reset (idempotency check)
      ravendb.ravendb.index:
        url: "http://{{ ansible_host }}:8080"
        database_name: "my_database"
        index_name: "Orders/ByCompany"
        mode: reset
