---
- name: Delete Index
  hosts: ravendb_nodes
  gather_facts: no

  roles:
    - community.ravendb.ravendb_python_client_prerequisites

  tasks:
    - name: Ensure RavenDB index is absent (check mode)
      community.ravendb.index:
        url: "http://{{ ansible_host }}:8080"
        database_name: "my_database"
        index_name: "UsersByName"
        state: absent
      check_mode: yes

    - name: Ensure RavenDB index is absent
      community.ravendb.index:
        url: "http://{{ ansible_host }}:8080"
        index_name: "UsersByName"
        database_name: "my_database"
        state: absent

    - name: Ensure RavenDB index is absent (idempotency check)
      community.ravendb.index:
        url: "http://{{ ansible_host }}:8080"
        index_name: "UsersByName"
        database_name: "my_database"
        state: absent