---
- name: Disable Index
  hosts: ravendb_nodes
  gather_facts: no

  roles:
    - community.ravendb.ravendb_python_client_prerequisites

  tasks:
    - name: Ensure RavenDB Index is disabled (check mode)
      community.ravendb.index:
        url: "http://{{ ansible_host }}:8080"
        database_name: "my_database"
        index_name: "Orders/ByCompany"
        mode: disabled
        cluster_wide: true
      check_mode: yes

    - name: Ensure RavenDB Index is disabled
      community.ravendb.index:
        url: "http://{{ ansible_host }}:8080"
        database_name: "my_database"
        index_name: "Orders/ByCompany"
        mode: disabled
        cluster_wide: true

    - name: Ensure RavenDB Index is disabled (idempotency check)
      community.ravendb.index:
        url: "http://{{ ansible_host }}:8080"
        database_name: "my_database"
        index_name: "Orders/ByCompany"
        mode: disabled
        cluster_wide: true
