---
- name: Enable Index
  hosts: ravendb_nodes
  gather_facts: no

  roles:
    - ravendb.ravendb.ravendb_python_client_prerequisites

  tasks:
    - name: Ensure RavenDB Index is enabled (check mode)
      ravendb.ravendb.index:
        url: "http://{{ ansible_host }}:8080"
        database_name: "my_database"
        index_name: "Orders/ByCompany"
        mode: enabled
        cluster_wide: true
      check_mode: yes

    - name: Ensure RavenDB Index is enabled
      ravendb.ravendb.index:
        url: "http://{{ ansible_host }}:8080"
        database_name: "my_database"
        index_name: "Orders/ByCompany"
        mode: enabled
        cluster_wide: true

    - name: Ensure RavenDB Index is enabled (idempotency check)
      ravendb.ravendb.index:
        url: "http://{{ ansible_host }}:8080"
        database_name: "my_database"
        index_name: "Orders/ByCompany"
        mode: enabled
        cluster_wide: true
