---
- name: Resume Index
  hosts: ravendb_nodes
  gather_facts: no

  roles:
    - ravendb.ravendb.ravendb_python_client_prerequisites

  tasks:
    - name: Ensure RavenDB Index is resumed (check mode)
      ravendb.ravendb.index:
        url: "http://{{ ansible_host }}:8080"
        database_name: "my_database"
        index_name: "Orders/ByCompany"
        mode: resumed
      check_mode: yes

    - name: Ensure RavenDB Index is resumed
      ravendb.ravendb.index:
        url: "http://{{ ansible_host }}:8080"
        database_name: "my_database"
        index_name: "Orders/ByCompany"
        mode: resumed

    - name: Ensure RavenDB Index is resumed (idempotency check)
      ravendb.ravendb.index:
        url: "http://{{ ansible_host }}:8080"
        database_name: "my_database"
        index_name: "Orders/ByCompany"
        mode: resumed
