---
- name: Delete Index
  hosts: ravendb_nodes
  gather_facts: no

  tasks:
    - name: Include Python prerequisites
      include_role:
        name: ravendb_node
        tasks_from: ravendb_python_prerequisites.yml

    - name: Ensure RavenDB index is absent (check mode)
      ravendb.community.index:
        url: "http://{{ ansible_host }}:8080"
        database_name: "my_database"
        index_name: "UsersByName"
        state: absent
      check_mode: yes

    - name: Ensure RavenDB index is absent
      ravendb.community.index:
        url: "http://{{ ansible_host }}:8080"
        index_name: "UsersByName"
        database_name: "my_database"
        state: absent

    - name: Ensure RavenDB index is absent (idempotency check)
      ravendb.community.index:
        url: "http://{{ ansible_host }}:8080"
        index_name: "UsersByName"
        database_name: "my_database"
        state: absent




