---
- name: Secured
  hosts: all
  tasks:
    - name: "Include ravendb_node"
      include_role:
        name: "ravendb_node"
      vars:
        ravendb_version: latest
        ravendb_version_minor: 6.2
        ravendb_release_channel: stable
        ravendb_arch: linux-x64
        ravendb_settings_preset: default
        ravendb_secured_enabled: true
        ravendb_license_file: "license.json"
        ravendb_admin_email: "omer@ravendb.net"
        ravendb_domain: "my-test-domain"
        ravendb_root_domain: "development.run"
