dependency:
  name: galaxy
driver:
  name: docker
  port_bindings:
    '8080': 80
    '38888': 38888
    '44443': 443
platforms:
  - name: centos
    image: thegoldenplatypus/custom-centos9-python39-privileged:latest
    pre_build_image: true
    privileged: true
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:rw'
    tmpfs:
      - /run
      - /tmp
    cgroupns_mode: host  
    command: /usr/sbin/init
lint: |
  set -e
  yamllint .
  ansible-lint
provisioner:
  name: ansible
  log: true
scenario:
  name: update-rhel
  test_sequence:
    - destroy
    - create
    - converge
    - verify
verifier:
  name: ansible
