---
- name: Form Cluster
  hosts: localhost
  gather_facts: no
  

  tasks:
    - name: Join Node B as Watcher
      ravendb.ravendb.node:
        node:
          tag: B
          type: "Watcher"
          url: "http://192.168.118.120:8080"
          leader_url: "http://192.168.117.90:8080"


    - name: Join Node C as Member
      ravendb.ravendb.node:
        node:
          tag: C
          url: "http://192.168.118.77:8080"
          leader_url: "http://192.168.117.90:8080"