---
- name: Create Database (secured server self signed)
  hosts: ravendb_nodes
  gather_facts: no

  tasks:
    - name: Include Python prerequisites
      include_role:
        name: ravendb.community.ravendb_node
        tasks_from: ravendb_python_client_prerequisites.yml
   
    - name: Ensure RavenDB database is present with secure connection (check mode)
      become: true
      ravendb.community.database:
        url:  "http://{{ ansible_host }}:443"
        database_name: "my_secured_database"
        replication_factor: 1
        secure: true
        certificate_path: "/etc/ravendb/security/combined_raven_cert.pem"
        ca_cert_path: "/etc/ravendb/security/ca_certificate.pem"
        state: present
      check_mode: yes

    - name: Ensure RavenDB database is present with secure connection
      become: true
      ravendb.community.database:
        url:  "http://{{ ansible_host }}:443"
        database_name: "my_secured_database"
        replication_factor: 1
        secure: true
        certificate_path: "/etc/ravendb/security/combined_raven_cert.pem"
        ca_cert_path: "/etc/ravendb/security/ca_certificate.pem"
        state: present

    - name: Ensure RavenDB database is present with secure connection (idempotency check)
      become: true
      ravendb.community.database:
        url:  "http://{{ ansible_host }}:443"
        database_name: "my_secured_database"
        replication_factor: 1
        secure: true
        certificate_path: "/etc/ravendb/security/combined_raven_cert.pem"
        ca_cert_path: "/etc/ravendb/security/ca_certificate.pem"
        state: present