---
- name: Create Database
  hosts: ravendb_nodes
  gather_facts: no

  roles:
    - ravendb.ravendb.ravendb_python_client_prerequisites

  tasks:
    - name: Ensure RavenDB database is present (check mode)
      ravendb.ravendb.database:
        url: "http://{{ ansible_host }}:8080"
        database_name: "my_database"
        replication_factor: 3
        state: present
      check_mode: yes

    - name: Ensure RavenDB database is present
      ravendb.ravendb.database:
        url: "http://{{ ansible_host }}:8080"
        database_name: "my_database"
        replication_factor: 3
        state: present

    - name: Ensure RavenDB database is present (idempotency check)
      ravendb.ravendb.database:
        url: "http://{{ ansible_host }}:8080"
        database_name: "my_database"
        replication_factor: 3
        state: present
