---
- name: Delete Database
  hosts: ravendb_nodes
  gather_facts: no

  roles:
    - community.ravendb.ravendb_python_client_prerequisites

  tasks:
    - name: Ensure RavenDB database is absent (check mode)
      community.ravendb.database:
        url: "http://{{ ansible_host }}:8080"
        database_name: "my_database"
        state: absent
      check_mode: yes

    - name: Ensure RavenDB database is absent
      community.ravendb.database:
        url: "http://{{ ansible_host }}:8080"
        database_name: "my_database"
        state: absent

    - name: Ensure RavenDB database is absent (idempotency check)
      community.ravendb.database:
        url: "http://{{ ansible_host }}:8080"
        database_name: "my_database"
        state: absent