---
- name: Create Database (secured server self signed)
  hosts: ravendb_nodes
  gather_facts: no

  roles:
    - community.ravendb.ravendb_python_client_prerequisites

  tasks:
    - name: Ensure RavenDB database is present with secure connection (check mode)
      become: true
      community.ravendb.database:
        url:  "http://{{ ansible_host }}:443"
        database_name: "my_secured_database"
        replication_factor: 1
        certificate_path: "/etc/ravendb/security/combined_raven_cert.pem"
        ca_cert_path: "/etc/ravendb/security/ca_certificate.pem"
        state: present
      check_mode: yes

    - name: Ensure RavenDB database is present with secure connection
      become: true
      community.ravendb.database:
        url:  "http://{{ ansible_host }}:443"
        database_name: "my_secured_database"
        replication_factor: 1
        certificate_path: "/etc/ravendb/security/combined_raven_cert.pem"
        ca_cert_path: "/etc/ravendb/security/ca_certificate.pem"
        state: present

    - name: Ensure RavenDB database is present with secure connection (idempotency check)
      become: true
      community.ravendb.database:
        url:  "http://{{ ansible_host }}:443"
        database_name: "my_secured_database"
        replication_factor: 1
        certificate_path: "/etc/ravendb/security/combined_raven_cert.pem"
        ca_cert_path: "/etc/ravendb/security/ca_certificate.pem"
        state: present