---
- name: Delete Database (secured server)
  hosts: ravendb_nodes
  gather_facts: no

  roles:
    - ravendb.ravendb.ravendb_python_client_prerequisites

  tasks:
    - name: Ensure RavenDB database is absent with secure connection (check mode)
      become: true
      ravendb.ravendb.database:
        url:  "http://{{ ansible_host }}:443"
        database_name: "my_secured_database"
        replication_factor: 1
        certificate_path: "/etc/ravendb/security/combined_raven_cert.pem"
        ca_cert_path: "/etc/ravendb/security/ca_certificate.pem"
        state: absent
      check_mode: yes

    - name: Ensure RavenDB database is absent with secure connection
      become: true
      ravendb.ravendb.database:
        url:  "http://{{ ansible_host }}:443"
        database_name: "my_secured_database"
        replication_factor: 1
        certificate_path: "/etc/ravendb/security/combined_raven_cert.pem"
        ca_cert_path: "/etc/ravendb/security/ca_certificate.pem"
        state: absent

    - name: Ensure RavenDB database is absent with secure connection (idempotency check)
      become: true
      ravendb.ravendb.database:
        url:  "http://{{ ansible_host }}:443"
        database_name: "my_secured_database"
        replication_factor: 1
        certificate_path: "/etc/ravendb/security/combined_raven_cert.pem"
        ca_cert_path: "/etc/ravendb/security/ca_certificate.pem"
        state: absent
        