---
- name: TODO
  hosts: all
  tasks:
    - name: "Include ravendb_node"
      include_role:
        name: "ravendb_node"
      vars:
        ravendb_version: "5.2.4"
        ravendb_settings_override:
          Security.UnsecuredAccessAllowed: "PublicNetwork"
          Indexing.MapBatchSize: 1024
          Logs.Mode: "Information"
