---
dependency:
  name: galaxy
driver:
  name: docker
  port_bindings:
    8080: 80
    44443: 443
    38888: 38888
platforms:
  - name: ubuntu-bionic
    image: jrei/systemd-ubuntu:18.04
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
      - /tmp
    command: /lib/systemd/systemd
lint: |
  set -e
  yamllint .
  ansible-lint
provisioner:
  name: ansible
  log: true
scenario:
  name: update
  idempotent: false
  test_sequence:
    - lint
    - destroy
    - create
    - converge
    - verify
verifier:
  name: ansible
