name: ravendb_node role tests 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - uses: actions/cache@v1
        id: cache
        with:
          path: .cache/pip
          key: ${{ runner.os }}-pip-2021-11-05
          restore-keys: |
            ${{ runner.os }}-test

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install molecule[docker] molecule
          pip install ansible yamllint ansible-lint jmespath

      - name: Run molecule unsecured scenario
        run: |
          cd roles/ravendb_node
          molecule test -s unsecured

      - name: Run molecule update scenario
        run: |
          cd roles/ravendb_node
          molecule test -s update

