name: ravendb_node role tests 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-debian-setup-scenarios:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible molecule molecule-docker docker

      - name: Set ansible roles path
        run: echo "ANSIBLE_ROLES_PATH=$GITHUB_WORKSPACE/roles" >> $GITHUB_ENV

      - name: Run molecule unsecured scenario
        working-directory: roles/ravendb_node
        run: molecule test -s unsecured
      
      - name: Run molecule update scenario
        working-directory: roles/ravendb_node
        run: molecule test -s update

      - name: Run molecule clenaup scenario
        working-directory: roles/ravendb_node
        run: molecule test -s cleanup

  test-rhel-setup-scenarios:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Python 3
          uses: actions/setup-python@v2
          with:
            python-version: "3.x"

        - name: Cache pip dependencies
          uses: actions/cache@v4
          with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip
            restore-keys: |
              ${{ runner.os }}-pip-

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install ansible molecule molecule-docker docker

        - name: Set ansible roles path
          run: echo "ANSIBLE_ROLES_PATH=$GITHUB_WORKSPACE/roles" >> $GITHUB_ENV

        - name: Run molecule unsecured-rhel scenario
          working-directory: roles/ravendb_node
          run: molecule test -s unsecured-rhel
        
        - name: Run molecule update-rhel scenario
          working-directory: roles/ravendb_node
          run: molecule test -s update-rhel

        - name: Run molecule clenaup-rhel scenario
          working-directory: roles/ravendb_node
          run: molecule test -s cleanup-rhel

  test-ravendb-modules:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Python 3
          uses: actions/setup-python@v2
          with:
            python-version: "3.x"

        - name: Cache pip dependencies
          uses: actions/cache@v4
          with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip
            restore-keys: |
              ${{ runner.os }}-pip-

        - name: Install ASP.NET Core Runtime
          run: |
            wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
            chmod +x dotnet-install.sh
            ./dotnet-install.sh --runtime aspnetcore --channel 8.0.0

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install ansible molecule molecule-docker docker ravendb_test_driver

        - name: Build ansible galaxy collection
          run: |
            ansible-galaxy collection build .
            ansible-galaxy collection install ./ravendb-community-*.tar.gz --force -p ./

        - name: Set up .NET environment variables
          run: |
            export DOTNET_ROOT=$HOME/.dotnet
            export PATH=$PATH:$HOME/.dotnet
            source ~/.bashrc

        - name: Change to ravendb_node role directory
          run: cd roles/ravendb_node

        - name: Run modules unit tests
          run: python3 -m unittest discover -s tests/unit -v
