name: ravendb_node role - unsecured setup test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install molecule[docker] molecule
          pip install ansible yamllint ansible-lint

      - name: Run molecule unsecured scenario
        run: |
          cd roles/ravendb_node
          molecule test -s unsecured

